using GitHubPRAssistant.Models;
using GitHubPRAssistant.Services;
using GitHubPRAssistant.Tools;

namespace GitHubPRAssistant.Agents;

public class PrReviewAgent
{
    private readonly CodeScannerTool _scanner;
    private readonly LlmService _llmService;
    private readonly GitHubService _githubService;
    private readonly ILogger<PrReviewAgent> _logger;
    private readonly AutomatedActionsService _automatedActionsService;

    public PrReviewAgent(
        CodeScannerTool scanner,
        LlmService llmService,
        GitHubService githubService,
        ILogger<PrReviewAgent> logger,
        AutomatedActionsService automatedActionsService
        )
    {
        _scanner = scanner;
        _llmService = llmService;
        _githubService = githubService;
        _logger = logger;
        _automatedActionsService = automatedActionsService;
    }

    public async Task<AgentResult> RunReviewAsync(PRContext prContext)
    {
        _logger.LogInformation("Starting PR review for {Owner}/{Repo} PR #{Number}",
            prContext.Owner, prContext.Repo, prContext.PrNumber);

        try
        {
            // Step 1: Get file summaries for LLM context
            var fileSummaries = prContext.ChangedFiles
                .Select(f => $"- {f.Path} (+{f.Added} -{f.Removed})")
                .ToList();

            // Step 2: Generate PR summary using LLM
            _logger.LogInformation("Generating PR summary...");
            var summary = await _llmService.SummarizePrAsync(
                prContext.PrTitle,
                prContext.PrDescription,
                fileSummaries
            );

            // Step 3: Run deterministic code scans
            _logger.LogInformation("Running code scanner...");
            var issues = await _scanner.ScanAsync(prContext);

            // Step 4: Generate final review comment
            _logger.LogInformation("Generating review comment...");
            var reviewComment = await _llmService.GenerateReviewCommentAsync(
                prContext.PrTitle,
                prContext.PrDescription,
                summary,
                issues
            );

            // Step 5: Add metadata footer
            var finalComment = FormatFinalComment(reviewComment, prContext, issues);

            var result = new AgentResult
            {
                Comment = finalComment,
                Summary = summary,
                Issues = issues,
                HasCriticalIssues = HasCriticalIssues(issues)
            };

            _logger.LogInformation("PR review completed: {IssueCount} issues, Critical: {HasCritical}",
                issues.Count, result.HasCriticalIssues);

            // Check for auto-approval
            var (shouldApprove, approvalReason) = await _automatedActionsService.EvaluateAutoApprovalAsync(
                prContext,
                result
            );

            if (shouldApprove)
            {
                await _automatedActionsService.ApprovePrAsync(prContext, approvalReason);
            }
            else if (result.HasCriticalIssues)
            {
                // Request changes for critical issues
                var criticalIssues = result.Issues
                    .Where(i => i.Contains("⚠️"))
                    .ToList();

                await _automatedActionsService.RequestChangesAsync(prContext, criticalIssues);
            }
            else
            {
                // Try to auto-fix minor issues
                var fixableIssues = result.Issues
                    .Where(i => i.Contains("console.log") || i.Contains("formatting"))
                    .ToList();

                if (fixableIssues.Any())
                {
                    await _automatedActionsService.AutoFixIssuesAsync(prContext, fixableIssues);
                }
            }

            return result;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to complete PR review");
            throw;
        }
    }

    private string FormatFinalComment(string reviewComment, PRContext context, List<string> issues)
    {
        var criticalCount = issues.Count(i => i.Contains("⚠️"));
        var warningCount = issues.Count - criticalCount;

        var footer = $@"

---
*🤖 Generated by AI PR Assistant*  
📊 **Stats:** {context.ChangedFiles.Count} files changed | {criticalCount} critical | {warningCount} warnings  
⏰ **Reviewed at:** {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC";

        return reviewComment + footer;
    }

    private bool HasCriticalIssues(List<string> issues)
    {
        var criticalKeywords = new[] { "secret", "password", "credential", "hardcoded ip" };
        return issues.Any(i => criticalKeywords.Any(k =>
            i.Contains(k, StringComparison.OrdinalIgnoreCase)));
    }
}